"use client";
import { useState } from "react";
const services=[["01","Interior Fit-Out","Complete fit-out solutions for offices, retail spaces, restaurants and residences—from concept to handover."],["02","Civil & Renovation","Renovation, partitions, ceilings, flooring, painting and structural improvement for existing spaces."],["03","MEP Works","Coordinated mechanical, electrical and plumbing services for safe, efficient everyday operation."],["04","Joinery","Custom cabinetry, counters, wall features and precision-made woodwork crafted around your space."],["05","Design & Planning","Practical layouts and detailed planning that bring clarity before construction begins."],["06","Project Management","One accountable team coordinating people, materials, quality and schedules from start to finish."]];
const projects=[["COMMERCIAL","Workplaces that work harder","project-one"],["RETAIL","Spaces built around experience","project-two"],["RESIDENTIAL","Interiors made for living","project-three"]];
export default function Home(){const[open,setOpen]=useState(false);const close=()=>setOpen(false);return <main>
<header className="site-header"><a className="brand" href="/"><span className="brand-mark"><i>E</i></span><span>EMBELLISH <b>DESIGN</b></span></a><button className="menu-button" onClick={()=>setOpen(!open)} aria-label="Toggle navigation"><span/><span/></button><nav className={open?"nav open":"nav"}><a href="/about" onClick={close}>About</a><a href="/services" onClick={close}>Services</a><a href="/projects" onClick={close}>Projects</a><a href="/contact" onClick={close}>Contact</a><a className="nav-cta" href="tel:+971525242962">Call us</a></nav></header>
<section className="hero" id="home"><div className="hero-copy"><p className="eyebrow">DUBAI · DESIGN & CONTRACTING</p><h1>We build spaces<br/>worth <em>remembering.</em></h1><p className="hero-text">Thoughtful design, dependable execution and one team from first sketch to final handover.</p><div className="hero-actions"><a className="button primary" href="/contact">Start your project <span>↗</span></a><a className="button text-button" href="/services">Explore services →</a></div></div><div className="hero-visual"><img src="https://lirp.cdn-website.com/441a4f95/dms3rep/multi/opt/luxury_dubai_office%2BInterior_concept_art_decor-1920w.webp" alt="Modern Dubai office interior fit-out"/><div className="hero-badge"><strong>Dubai</strong><span>Built with care</span></div></div></section>
<section className="intro" id="about"><div><p className="eyebrow">ABOUT EMBELLISH</p><h2>Clear thinking.<br/>Crafted spaces.</h2></div><div className="intro-copy"><p>Embellish Design is a Dubai-based design and contracting company delivering functional, refined spaces across commercial, residential and retail projects.</p><p>We combine careful planning, skilled workmanship and straightforward communication so every project moves with confidence.</p><div className="values"><span><b>01</b>Detail-led</span><span><b>02</b>Dependable</span><span><b>03</b>Built to last</span></div></div></section>
<section className="services" id="services"><div className="section-heading"><p className="eyebrow">WHAT WE DO</p><h2>From idea to<br/><em>finished space.</em></h2></div><div className="service-grid">{services.map(s=><article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><i>↗</i></article>)}</div></section>
<section className="process"><p className="eyebrow">HOW WE WORK</p><div className="process-grid"><h2>Simple process.<br/><em>Solid results.</em></h2><ol>{[["01","Understand","We listen, visit the site and define what success looks like."],["02","Plan","We align the design, scope, budget and delivery schedule."],["03","Build","Our team coordinates execution with quality checks throughout."],["04","Handover","We inspect and deliver your space ready to use."]].map(x=><li key={x[0]}><b>{x[0]}</b><div><strong>{x[1]}</strong><span>{x[2]}</span></div></li>)}</ol></div></section>
<section className="projects" id="projects"><div className="section-heading light"><p className="eyebrow">OUR WORK</p><h2>Built around<br/><em>your ambitions.</em></h2></div><div className="project-grid">{projects.map((p,i)=><article className={p[2]} key={p[0]}><span>{p[0]}</span><h3>{p[1]}</h3><b>0{i+1}</b></article>)}</div></section>
<section className="contact" id="contact"><div><p className="eyebrow">LET’S TALK</p><h2>Have a space<br/>in mind?</h2><p>Tell us what you’re planning. We’ll help you find the clearest route from idea to reality.</p></div><div className="contact-panel"><a href="tel:+971525242962"><small>CALL</small><strong>+971 52 524 2962</strong><span>↗</span></a><a href="https://wa.me/971525242962?text=Hello%20Embellish%20Design%2C%20I%20would%20like%20to%20discuss%20a%20project." target="_blank" rel="noreferrer"><small>WHATSAPP</small><strong>Message our team</strong><span>↗</span></a><a href="mailto:info@embellishdesign.com"><small>EMAIL</small><strong>info@embellishdesign.com</strong><span>↗</span></a><div><small>VISIT</small><strong>Business Bay, Dubai</strong></div></div></section>
<footer><a className="brand" href="#home"><span className="brand-mark"><i>E</i></span><span>EMBELLISH <b>DESIGN</b></span></a><p>Design · Fit-Out · Contracting</p><p>© 2026 Embellish Design</p></footer><a className="whatsapp-float" href="https://wa.me/971525242962" target="_blank" rel="noreferrer">WA</a></main>}
