import Image from "next/image";
import Link from "next/link";
import { processSteps, projects, services } from "@/lib/content";

export default function Home() {
  return <main>
    <section className="hero">
      <div className="hero-copy"><p className="eyebrow">DUBAI · CONSTRUCTION & CONTRACTING</p><h1>Spaces shaped<br />with <em>purpose.</em></h1><p className="hero-text">Construction, demolition, landscaping and swimming-pool works delivered by one accountable team—from the first site visit to final handover.</p><div className="hero-actions"><Link className="button primary" href="/contact">Start your project <span>↗</span></Link><Link className="button text-button" href="/projects">View selected work →</Link></div><div className="hero-proof"><span><b>01</b> One team</span><span><b>02</b> Clear delivery</span><span><b>03</b> Built to last</span></div></div>
      <div className="hero-visual"><Image src="/embellish-team-site.webp" alt="Embellish Design team wearing branded safety vests on a Dubai construction site" fill priority sizes="(max-width: 850px) 100vw, 50vw" /><div className="hero-badge"><strong>Dubai</strong><span>Construction · Landscape · Pools</span></div></div>
    </section>
    <section className="intro"><div><p className="eyebrow">ABOUT EMBELLISH</p><h2>Clear thinking.<br />Crafted spaces.</h2></div><div className="intro-copy"><p>Embellish Design is a Dubai-based design and contracting company creating functional, refined environments for business, retail, hospitality and home.</p><p>We bring planning, technical coordination and construction together. That means fewer gaps, faster decisions and one team responsible for the finished result.</p><Link className="inline-link" href="/about">Meet the team and our approach →</Link></div></section>
    <section className="services"><div className="section-heading"><div><p className="eyebrow">WHAT WE DO</p><h2>From idea to<br /><em>finished space.</em></h2></div><Link className="inline-link" href="/services">Explore all services →</Link></div><div className="service-grid">{services.map((service) => <Link href={`/services/${service.slug}`} key={service.slug}><article><span>{service.number}</span><h3>{service.title}</h3><p>{service.short}</p><i>↗</i></article></Link>)}</div></section>
    <section className="process"><p className="eyebrow">HOW WE WORK</p><div className="process-grid"><h2>Simple process.<br /><em>Solid results.</em></h2><ol>{processSteps.map(([number, title, text]) => <li key={number}><b>{number}</b><div><strong>{title}</strong><span>{text}</span></div></li>)}</ol></div></section>
    <section className="projects"><div className="section-heading light"><div><p className="eyebrow">SELECTED WORK</p><h2>Built around<br /><em>your ambitions.</em></h2></div><Link className="inline-link" href="/projects">View all projects →</Link></div><div className="project-grid">{projects.slice(0, 3).map((project, index) => <Link href={`/projects/${project.slug}`} key={project.slug} className={index === 0 ? "project-featured" : ""}><article><Image src={project.cover} alt={project.title} fill sizes={index === 0 ? "(max-width: 850px) 100vw, 62vw" : "(max-width: 850px) 100vw, 38vw"} /><div className="project-overlay"><span>{project.category}</span><h3>{project.title}</h3><b>{project.number}</b></div></article></Link>)}</div></section>
    <section className="contact"><div><p className="eyebrow">LET’S TALK</p><h2>Have a space<br />in mind?</h2><p>Tell us what you are planning. We will help you find the clearest route from idea to reality.</p></div><div className="contact-panel"><a href="tel:+971525242962"><small>CALL</small><strong>+971 52 524 2962</strong><span>↗</span></a><a href="https://wa.me/971525242962" target="_blank" rel="noreferrer"><small>WHATSAPP</small><strong>Message our team</strong><span>↗</span></a><a href="mailto:info@embellishdesign.com"><small>EMAIL</small><strong>info@embellishdesign.com</strong><span>↗</span></a><div><small>VISIT</small><strong>Business Bay, Dubai</strong></div></div></section>
  </main>;
}
